### ISSUE TITLE
Traqball freezing in Chrome

### ISSUE THREAD

**Issue by mandulaj** [dirkweber/traqball.js#7]
I am using _Chrome 34.0.1847.131_. The rotation works well! However when I do a sudden quick mouse drag the rotation freezes. **No error in console!** The only fix is refreshing. I even tried `ball.activate();` It doesn't work. I find that the smaller the object, the more common the error. It might be that the number change too fast and go out of bounds. I haven't tried other browsers yet...

**Comment by mandulaj** [comment]
UPDATE: Firefox has no problem. I also found that it happens during the following event: If the 3D object is dragged quickly so that it keeps its momentum and keeps spinning for a bit if it is clicked again while it is still moving, ball freezes.

**Comment by dirkweber** [comment]
Hi, can I have a peek at the file?

**Comment by mandulaj** [comment]
I am sorry! Today in the morning I tried again and all worked, guess Chrome bug. BTW it was also happening on your demo... Therefor I thought it was the fault of treqball.js. You can check my Repo https://github.com/zpiman/PiDashboard.js/blob/express/src/js/script.js I am sorry for bothering you :smiley:

**Comment by mandulaj** [comment]
Hmm... that is weird! Now in the evening it is stuck again... I guess I will post it on the Chrome issues. It looks like there is no problem with your `traqball.js` therefore I see no reason for keeping this issue open.

**Comment by ghost** [comment]
Sorry for my english... :)

I think the problem is in line 72 (window.setTimeout (callback, 17);), because when I delete it, chrome doesn't freezes.
I know that it is a callback, but must be another way to run it...

**Comment by dirkweber** [comment]
Hm, this line kicks in when the browser doesn't know requestanimationframe, which definetely isn't the case for chrome. I tried to reproduce this bug but was not able to. In which file file did it show up? One of the demos or something you created?

**Comment by ghost** [comment]
I think it was a demo file from the directory src. 
An error occurs when trying to quickly accelerates the object by many clicks by mouse. It freezes when an object rotates and even clicking on it...
